package com.b_tree.telartes.Entidades;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "ACTUALIZACION".
 */
public class Actualizacion {

    private Long id;
    /** Not-null value. */
    private String Nombre;
    /** Not-null value. */
    private String Fecha;
    private int idActual;

    public Actualizacion() {
    }

    public Actualizacion(Long id) {
        this.id = id;
    }

    public Actualizacion(Long id, String Nombre, String Fecha, int idActual) {
        this.id = id;
        this.Nombre = Nombre;
        this.Fecha = Fecha;
        this.idActual = idActual;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return Nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    /** Not-null value. */
    public String getFecha() {
        return Fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(String Fecha) {
        this.Fecha = Fecha;
    }

    public int getIdActual() {
        return idActual;
    }

    public void setIdActual(int idActual) {
        this.idActual = idActual;
    }

}
