package com.b_tree.telartes.Entidades;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import org.json.JSONObject;

import java.io.Serializable;

/**
 * Entity mapped to table "AGENDA_CULTURAL".
 */
public class AgendaCultural implements Serializable{

    private Long id;
    private int nid;
    /** Not-null value. */
    private String titulo;
    private String campo;
    private String descripcion;
    private String fecha;
    private String imagen;
    private String costo;
    private String departamento;
    private String enlace;
    private String fechainicio;
    private String fechafin;
    private String lugar_direccion;
    private String archivo;
    private String enviado_por;

    public AgendaCultural() {
    }

    public AgendaCultural(Long id) {
        this.id = id;
    }

    public AgendaCultural(Long id, int nid, String titulo, String campo, String descripcion, String fecha, String imagen, String costo, String departamento, String enlace, String fechainicio, String fechafin, String lugar_direccion, String archivo, String enviado_por) {
        this.id = id;
        this.nid = nid;
        this.titulo = titulo;
        this.campo = campo;
        this.descripcion = descripcion;
        this.fecha = fecha;
        this.imagen = imagen;
        this.costo = costo;
        this.departamento = departamento;
        this.enlace = enlace;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.lugar_direccion = lugar_direccion;
        this.archivo = archivo;
        this.enviado_por = enviado_por;
    }


    public AgendaCultural(JSONObject jsonObject){
        try {
            titulo = android.text.Html.fromHtml(jsonObject.getString("node_title")).toString();
            campo =  android.text.Html.fromHtml(jsonObject.getString("campo")).toString();
            costo = jsonObject.getString("costo");
            departamento =  android.text.Html.fromHtml(jsonObject.getString("departamento")).toString();
            descripcion = jsonObject.getString("descripción");
            enlace =    jsonObject.getString("enlace");
            lugar_direccion =  jsonObject.getString("lugar/dirección");
            archivo =  android.text.Html.fromHtml(jsonObject.getString("pdf")).toString();
            this.nid = Integer.parseInt(jsonObject.getString("nid"));
            fecha =  android.text.Html.fromHtml(jsonObject.getString("fecha inicio")).toString();
            enviado_por = jsonObject.getString("enviado por");
            fechainicio =  android.text.Html.fromHtml(jsonObject.getString("fecha inicio")).toString();
            fechafin =  android.text.Html.fromHtml(jsonObject.getString("fecha fin")).toString();
            this.imagen = (jsonObject.getString("imagen"));
            int start = imagen.indexOf("src=\"") + 5;
            int end = imagen.indexOf("\"", start);
            String src = imagen.substring(start, end);
            this.imagen=src;
        }catch (Exception e){
            Log.d("Error json", e.getMessage());
        }

    }
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getNid() {
        return nid;
    }

    public void setNid(int nid) {
        this.nid = nid;
    }

    /** Not-null value. */
    public String getTitulo() {
        return titulo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getCampo() {
        return campo;
    }

    public void setCampo(String campo) {
        this.campo = campo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public String getCosto() {
        return costo;
    }

    public void setCosto(String costo) {
        this.costo = costo;
    }

    public String getDepartamento() {
        return departamento;
    }

    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    public String getEnlace() {
        return enlace;
    }

    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }

    public String getFechainicio() {
        return fechainicio;
    }

    public void setFechainicio(String fechainicio) {
        this.fechainicio = fechainicio;
    }

    public String getFechafin() {
        return fechafin;
    }

    public void setFechafin(String fechafin) {
        this.fechafin = fechafin;
    }

    public String getLugar_direccion() {
        return lugar_direccion;
    }

    public void setLugar_direccion(String lugar_direccion) {
        this.lugar_direccion = lugar_direccion;
    }

    public String getArchivo() {
        return archivo;
    }

    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }

    public String getEnviado_por() {
        return enviado_por;
    }

    public void setEnviado_por(String enviado_por) {
        this.enviado_por = enviado_por;
    }

}
