package com.b_tree.telartes.Entidades;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.util.Log;

import org.json.JSONObject;

/**
 * Entity mapped to table "CATEGORIA".
 */
public class Categoria {

    private Long id;
    /** Not-null value. */
    private String Nombre;
    /** Not-null value. */
    private String Vocabulario;

    public Categoria() {
    }

    public Categoria(Long id) {
        this.id = id;
    }
    public Categoria(JSONObject jsonObject){
        try {
            this.Nombre = android.text.Html.fromHtml(jsonObject.getString("categoria")).toString();
            this.Vocabulario =  android.text.Html.fromHtml(jsonObject.getString("vocabulario")).toString();

        }catch (Exception e){
            Log.d("Error json", e.getMessage());
        }
    }

    public Categoria(Long id, String Nombre, String Vocabulario) {
        this.id = id;
        this.Nombre = Nombre;
        this.Vocabulario = Vocabulario;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return Nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    /** Not-null value. */
    public String getVocabulario() {
        return Vocabulario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVocabulario(String Vocabulario) {
        this.Vocabulario = Vocabulario;
    }

}
