package com.b_tree.telartes.Entidades;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.b_tree.telartes.Entidades.Convocatoria;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONVOCATORIA".
*/
public class ConvocatoriaDao extends AbstractDao<Convocatoria, Long> {

    public static final String TABLENAME = "CONVOCATORIA";

    /**
     * Properties of entity Convocatoria.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nid = new Property(1, int.class, "nid", false, "NID");
        public final static Property Titulo = new Property(2, String.class, "titulo", false, "TITULO");
        public final static Property Fechalimite = new Property(3, String.class, "fechalimite", false, "FECHALIMITE");
        public final static Property Descripcion = new Property(4, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Lugar = new Property(5, String.class, "lugar", false, "LUGAR");
        public final static Property Archivo = new Property(6, String.class, "archivo", false, "ARCHIVO");
        public final static Property Imagen = new Property(7, String.class, "imagen", false, "IMAGEN");
        public final static Property Areas = new Property(8, String.class, "areas", false, "AREAS");
        public final static Property Campo = new Property(9, String.class, "campo", false, "CAMPO");
        public final static Property Categoria = new Property(10, String.class, "categoria", false, "CATEGORIA");
        public final static Property Convocante = new Property(11, String.class, "convocante", false, "CONVOCANTE");
        public final static Property Fechafin = new Property(12, String.class, "fechafin", false, "FECHAFIN");
        public final static Property Direccionweb = new Property(13, String.class, "direccionweb", false, "DIRECCIONWEB");
        public final static Property Correo = new Property(14, String.class, "correo", false, "CORREO");
        public final static Property Enviado_por = new Property(15, String.class, "enviado_por", false, "ENVIADO_POR");
    };


    public ConvocatoriaDao(DaoConfig config) {
        super(config);
    }
    
    public ConvocatoriaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONVOCATORIA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NID\" INTEGER NOT NULL ," + // 1: nid
                "\"TITULO\" TEXT NOT NULL ," + // 2: titulo
                "\"FECHALIMITE\" TEXT," + // 3: fechalimite
                "\"DESCRIPCION\" TEXT," + // 4: descripcion
                "\"LUGAR\" TEXT," + // 5: lugar
                "\"ARCHIVO\" TEXT," + // 6: archivo
                "\"IMAGEN\" TEXT," + // 7: imagen
                "\"AREAS\" TEXT," + // 8: areas
                "\"CAMPO\" TEXT," + // 9: campo
                "\"CATEGORIA\" TEXT," + // 10: categoria
                "\"CONVOCANTE\" TEXT," + // 11: convocante
                "\"FECHAFIN\" TEXT," + // 12: fechafin
                "\"DIRECCIONWEB\" TEXT," + // 13: direccionweb
                "\"CORREO\" TEXT," + // 14: correo
                "\"ENVIADO_POR\" TEXT);"); // 15: enviado_por
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONVOCATORIA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Convocatoria entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNid());
        stmt.bindString(3, entity.getTitulo());
 
        String fechalimite = entity.getFechalimite();
        if (fechalimite != null) {
            stmt.bindString(4, fechalimite);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(5, descripcion);
        }
 
        String lugar = entity.getLugar();
        if (lugar != null) {
            stmt.bindString(6, lugar);
        }
 
        String archivo = entity.getArchivo();
        if (archivo != null) {
            stmt.bindString(7, archivo);
        }
 
        String imagen = entity.getImagen();
        if (imagen != null) {
            stmt.bindString(8, imagen);
        }
 
        String areas = entity.getAreas();
        if (areas != null) {
            stmt.bindString(9, areas);
        }
 
        String campo = entity.getCampo();
        if (campo != null) {
            stmt.bindString(10, campo);
        }
 
        String categoria = entity.getCategoria();
        if (categoria != null) {
            stmt.bindString(11, categoria);
        }
 
        String convocante = entity.getConvocante();
        if (convocante != null) {
            stmt.bindString(12, convocante);
        }
 
        String fechafin = entity.getFechafin();
        if (fechafin != null) {
            stmt.bindString(13, fechafin);
        }
 
        String direccionweb = entity.getDireccionweb();
        if (direccionweb != null) {
            stmt.bindString(14, direccionweb);
        }
 
        String correo = entity.getCorreo();
        if (correo != null) {
            stmt.bindString(15, correo);
        }
 
        String enviado_por = entity.getEnviado_por();
        if (enviado_por != null) {
            stmt.bindString(16, enviado_por);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Convocatoria readEntity(Cursor cursor, int offset) {
        Convocatoria entity = new Convocatoria( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // nid
            cursor.getString(offset + 2), // titulo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // fechalimite
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // descripcion
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // lugar
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // archivo
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // imagen
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // areas
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // campo
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // categoria
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // convocante
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // fechafin
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // direccionweb
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // correo
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15) // enviado_por
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Convocatoria entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNid(cursor.getInt(offset + 1));
        entity.setTitulo(cursor.getString(offset + 2));
        entity.setFechalimite(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDescripcion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLugar(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setArchivo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImagen(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setAreas(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCampo(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCategoria(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setConvocante(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setFechafin(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setDireccionweb(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCorreo(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setEnviado_por(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Convocatoria entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Convocatoria entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
