 package com.b_tree.telartes.Entidades;

 import android.util.Log;

 import org.json.JSONObject;

 import java.io.Serializable;

 ;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

 /**
  * Entity mapped to table "CONVOCATORIA".
  */
 public class Convocatoria implements Serializable{

     private Long id;
     private int nid;
     /** Not-null value. */
     private String titulo;
     private String fechalimite;
     private String descripcion;
     private String lugar;
     private String archivo;
     private String imagen;
     private String areas;
     private String campo;
     private String categoria;
     private String convocante;
     private String fechafin;
     private String direccionweb;
     private String correo;
     private String enviado_por;

     public Convocatoria() {
     }

     public Convocatoria(Long id) {
         this.id = id;
     }

     public Convocatoria(Long id, int nid, String titulo, String fechalimite, String descripcion, String lugar, String archivo, String imagen, String areas, String campo, String categoria, String convocante, String fechafin, String direccionweb, String correo, String enviado_por) {
         this.id = id;
         this.nid = nid;
         this.titulo = titulo;
         this.fechalimite = fechalimite;
         this.descripcion = descripcion;
         this.lugar = lugar;
         this.archivo = archivo;
         this.imagen = imagen;
         this.areas = areas;
         this.campo = campo;
         this.categoria = categoria;
         this.convocante = convocante;
         this.fechafin = fechafin;
         this.direccionweb = direccionweb;
         this.correo = correo;
         this.enviado_por = enviado_por;
     }


     public Convocatoria(JSONObject jsonObject){
         try {

             this.titulo = android.text.Html.fromHtml(jsonObject.getString("node_title")).toString();
             this.categoria = android.text.Html.fromHtml(jsonObject.getString("categoría")).toString();
             this.correo = jsonObject.getString("correo electrónico");
             this.descripcion = android.text.Html.fromHtml(jsonObject.getString("descripcion")).toString();
             this.direccionweb = android.text.Html.fromHtml(jsonObject.getString("dirección web")).toString();
             this.archivo =  jsonObject.getString("archivo pdf");
             this.imagen = (jsonObject.getString("imagen"));
             int start = imagen.indexOf("src=\"") + 5;
             int end = imagen.indexOf("\"", start);
             String src = imagen.substring(start, end);
             this.imagen=src;
             this.areas= android.text.Html.fromHtml(jsonObject.getString("areas")).toString();
             this.campo = android.text.Html.fromHtml(jsonObject.getString("campos")).toString();
             this.convocante = android.text.Html.fromHtml(jsonObject.getString("convocante")).toString();
             this.fechalimite = android.text.Html.fromHtml(jsonObject.getString("fecha limite")).toString();
             this.lugar = android.text.Html.fromHtml(jsonObject.getString("ciudad")).toString();
             this.correo  = android.text.Html.fromHtml(jsonObject.getString("correo electrónico")).toString();
             this.nid = Integer.parseInt(jsonObject.getString("nid"));
         }catch (Exception e){
             Log.d("Error json", e.getMessage());
         }
     }
     public Long getId() {
         return id;
     }

     public void setId(Long id) {
         this.id = id;
     }

     public int getNid() {
         return nid;
     }

     public void setNid(int nid) {
         this.nid = nid;
     }

     /** Not-null value. */
     public String getTitulo() {
         return titulo;
     }

     /** Not-null value; ensure this value is available before it is saved to the database. */
     public void setTitulo(String titulo) {
         this.titulo = titulo;
     }

     public String getFechalimite() {
         return fechalimite;
     }

     public void setFechalimite(String fechalimite) {
         this.fechalimite = fechalimite;
     }

     public String getDescripcion() {
         return descripcion;
     }

     public void setDescripcion(String descripcion) {
         this.descripcion = descripcion;
     }

     public String getLugar() {
         return lugar;
     }

     public void setLugar(String lugar) {
         this.lugar = lugar;
     }

     public String getArchivo() {
         return archivo;
     }

     public void setArchivo(String archivo) {
         this.archivo = archivo;
     }

     public String getImagen() {
         return imagen;
     }

     public void setImagen(String imagen) {
         this.imagen = imagen;
     }

     public String getAreas() {
         return areas;
     }

     public void setAreas(String areas) {
         this.areas = areas;
     }

     public String getCampo() {
         return campo;
     }

     public void setCampo(String campo) {
         this.campo = campo;
     }

     public String getCategoria() {
         return categoria;
     }

     public void setCategoria(String categoria) {
         this.categoria = categoria;
     }

     public String getConvocante() {
         return convocante;
     }

     public void setConvocante(String convocante) {
         this.convocante = convocante;
     }

     public String getFechafin() {
         return fechafin;
     }

     public void setFechafin(String fechafin) {
         this.fechafin = fechafin;
     }

     public String getDireccionweb() {
         return direccionweb;
     }

     public void setDireccionweb(String direccionweb) {
         this.direccionweb = direccionweb;
     }

     public String getCorreo() {
         return correo;
     }

     public void setCorreo(String correo) {
         this.correo = correo;
     }

     public String getEnviado_por() {
         return enviado_por;
     }

     public void setEnviado_por(String enviado_por) {
         this.enviado_por = enviado_por;
     }

 }
