package com.b_tree.telartes.Entidades;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.b_tree.telartes.Entidades.AgendaCultural;
import com.b_tree.telartes.Entidades.Noticia;
import com.b_tree.telartes.Entidades.Convocatoria;

import com.b_tree.telartes.Entidades.AgendaCulturalDao;
import com.b_tree.telartes.Entidades.NoticiaDao;
import com.b_tree.telartes.Entidades.ConvocatoriaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig agendaCulturalDaoConfig;
    private final DaoConfig noticiaDaoConfig;
    private final DaoConfig convocatoriaDaoConfig;

    private final AgendaCulturalDao agendaCulturalDao;
    private final NoticiaDao noticiaDao;
    private final ConvocatoriaDao convocatoriaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        agendaCulturalDaoConfig = daoConfigMap.get(AgendaCulturalDao.class).clone();
        agendaCulturalDaoConfig.initIdentityScope(type);

        noticiaDaoConfig = daoConfigMap.get(NoticiaDao.class).clone();
        noticiaDaoConfig.initIdentityScope(type);

        convocatoriaDaoConfig = daoConfigMap.get(ConvocatoriaDao.class).clone();
        convocatoriaDaoConfig.initIdentityScope(type);

        agendaCulturalDao = new AgendaCulturalDao(agendaCulturalDaoConfig, this);
        noticiaDao = new NoticiaDao(noticiaDaoConfig, this);
        convocatoriaDao = new ConvocatoriaDao(convocatoriaDaoConfig, this);

        registerDao(AgendaCultural.class, agendaCulturalDao);
        registerDao(Noticia.class, noticiaDao);
        registerDao(Convocatoria.class, convocatoriaDao);
    }
    
    public void clear() {
        agendaCulturalDaoConfig.getIdentityScope().clear();
        noticiaDaoConfig.getIdentityScope().clear();
        convocatoriaDaoConfig.getIdentityScope().clear();
    }

    public AgendaCulturalDao getAgendaCulturalDao() {
        return agendaCulturalDao;
    }

    public NoticiaDao getNoticiaDao() {
        return noticiaDao;
    }

    public ConvocatoriaDao getConvocatoriaDao() {
        return convocatoriaDao;
    }

}
