package com.b_tree.telartes.Entidades;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.b_tree.telartes.Entidades.Convocatoria;

import com.b_tree.telartes.Entidades.ConvocatoriaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig convocatoriaDaoConfig;

    private final ConvocatoriaDao convocatoriaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        convocatoriaDaoConfig = daoConfigMap.get(ConvocatoriaDao.class).clone();
        convocatoriaDaoConfig.initIdentityScope(type);

        convocatoriaDao = new ConvocatoriaDao(convocatoriaDaoConfig, this);

        registerDao(Convocatoria.class, convocatoriaDao);
    }
    
    public void clear() {
        convocatoriaDaoConfig.getIdentityScope().clear();
    }

    public ConvocatoriaDao getConvocatoriaDao() {
        return convocatoriaDao;
    }

}
